remote_theme: "mmistakes/minimal-mistakes@4.26.2"

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" #(default), "github-dark"
    issue_term: "pathname"
    crossorigin: "anonymous"
    
# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
